### ISSUE TITLE
secondary key coming up as unavailable when device not in use

### ISSUE THREAD

**Issue by stagea09** [benct/lovelace-attribute-entity-row#1]
- entity: switch.dishwasher_switch
    type: 'custom:attribute-entity-row'
    toggle: true
    secondary:
      key: power_consumption
      unit: kw

this works fine when the device is in use but when the power consumption is 0 it displays as unavailable kw.

ideas?

**Comment by benct** [comment]
That's a bug in the card code. I'll push a fix for that in a sec.

I would recommend looking at [multiple-entity-row](https://github.com/benct/lovelace-multiple-entity-row) instead though, as that is better and more maintained version of this card.
